# Generated by Django 5.1.3 on 2026-02-13 13:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('area_sqm', models.FloatField(help_text='Property area in square meters', validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(10000.0)])),
                ('rooms', models.PositiveSmallIntegerField(help_text='Number of rooms', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValuationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_price', models.BigIntegerField(help_text='Estimated property price in local currency')),
                ('price_per_sqm', models.IntegerField(help_text='Estimated price per square meter')),
                ('model_version', models.CharField(default='v1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='valuation.valuationrequest')),
            ],
        ),
    ]
