"""
Django settings for valuation_api project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY should be set in local_settings.py
# If local_settings.py doesn't exist, this will cause an error (which is good!)
SECRET_KEY = None


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False  # Safe default - will be overridden by local_settings.py

ALLOWED_HOSTS = []  # Empty default - will be overridden by local_settings.py

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'valuation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'valuation_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'valuation_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for serving static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Import local settings - explicit imports for better control and clarity
try:
    from .local_settings import (
        SECRET_KEY as LOCAL_SECRET_KEY,
        DEBUG as LOCAL_DEBUG,
        ALLOWED_HOSTS as LOCAL_ALLOWED_HOSTS,
        # Database settings
        DATABASES as LOCAL_DATABASES,
        # Cache settings
        CACHES as LOCAL_CACHES,
        # Celery settings
        CELERY_BROKER_URL,
        CELERY_RESULT_BACKEND,
        CELERY_ACCEPT_CONTENT,
        CELERY_TASK_SERIALIZER,
        CELERY_RESULT_SERIALIZER,
        CELERY_TIMEZONE,
    )
    # Apply local settings
    SECRET_KEY = LOCAL_SECRET_KEY
    DEBUG = LOCAL_DEBUG
    ALLOWED_HOSTS = LOCAL_ALLOWED_HOSTS
    DATABASES = LOCAL_DATABASES
    
    # Apply cache settings if provided
    if 'LOCAL_CACHES' in locals():
        CACHES = LOCAL_CACHES
        
except ImportError:
    # No local_settings.py file found - this is normal in Docker containers
    # Environment variables will override defaults below
    pass

# Override database settings with environment variables if present (for Docker containers)
import os
if 'DATABASE_URL' in os.environ:
    # Simple parsing of postgresql://user:pass@host:port/db
    # DATABASE_URL = postgresql://postgres:postgres123@database:5432/real_estate_db
    url = os.environ['DATABASE_URL']
    if url.startswith('postgresql://'):
        # Extract components: postgresql://user:pass@host:port/db
        url = url.replace('postgresql://', '')
        auth, host_db = url.split('@')
        user, password = auth.split(':')
        host_port, db_name = host_db.split('/')
        host, port = host_port.split(':')
        
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': db_name,
                'USER': user,
                'PASSWORD': password,
                'HOST': host,
                'PORT': port,
                'OPTIONS': {
                    'connect_timeout': 10,
                },
            }
        }

# Override other settings with environment variables if present (for Docker containers)
if 'SECRET_KEY' in os.environ:
    SECRET_KEY = os.environ['SECRET_KEY']

if 'DEBUG' in os.environ:
    DEBUG = os.environ['DEBUG'].lower() in ('true', '1', 'yes', 'on')

if 'ALLOWED_HOSTS' in os.environ:
    ALLOWED_HOSTS = [host.strip() for host in os.environ['ALLOWED_HOSTS'].split(',')]

# Override ML service URL with environment variable if present (for Docker containers)
if 'ML_SERVICE_URL' in os.environ:
    ML_SERVICE_URL = os.environ['ML_SERVICE_URL']

# Final validation - SECRET_KEY must be set either in local_settings.py or environment variable
if SECRET_KEY is None:
    raise Exception("config error: SECRET_KEY must be set either in local_settings.py or as environment variable")
